name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Login to Docker Registry
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: crpi-emxch7mwa2o3l86d.cn-hangzhou.personal.cr.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t crpi-emxch7mwa2o3l86d.cn-hangzhou.personal.cr.aliyuncs.com/your-image-name:latest .

      # Step 4: Push Docker Image to Registry
      - name: Push Docker Image
        run: |
          docker push crpi-emxch7mwa2o3l86d.cn-hangzhou.personal.cr.aliyuncs.com/your-image-name:latest
